version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - env.config.prod-test
    volumes:
      - ./users.db:/app/users.db

  frontend:
    build: ./auth-app-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
