services:
  - type: web
    name: auth-app-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRES_MINUTES
        value: 30
      - key: ACCESS_TOKEN_EXPIRES_DAYS
        value: 7
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health

  - type: web
    name: auth-app-frontend
    env: static
    buildCommand: cd auth-app-frontend && npm install && npm run build
    staticPublishPath: auth-app-frontend/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://auth-app-backend-udya.onrender.com/api/*