"""add_case_insensitive_email_index

Revision ID: fec1c6b1b996
Revises: c6aa3f945d9b
Create Date: 2025-08-07 22:53:26.205903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec1c6b1b996'
down_revision: Union[str, Sequence[str], None] = 'c6aa3f945d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
